version: '3.1'
services:
  dev_server:
    image: lotosbin/idea_generic_task_server
    build:
      context: .
      dockerfile: idea_generic_task_server/Dockerfile
    env_file:
      - ./.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
  prd_server:
    image: lotosbin/idea_generic_task_server
    environment:
      - ASPNETCORE_ZENTAO_HOST=https://demo.zentao.pm/
    ports:
      - "5000:80"